# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 433413877d78e615cbb0078e9f72583068ea0b23f77d7b0e8e1208d1dffaa514c6728c44a01d66d7f6e0c49528a731d510e0dce74d0a0cb182a63b4be8feeba6

test:
  secret_key_base: 7ae5be9432a0793773431127a6350b173b3b18eaa20cfb0ea6adf7e5a35c7ea6470b03a3f63c1b3fa398240f244439b74451fd6194c8af32b3405e002511d7b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
